# Generated by Django 4.2.10 on 2025-02-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dw_analytics', '0008_rename_assignment_group_id_incident_assignment_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('is_contrato_lancado', models.BooleanField(default=False, help_text='Contrato foi lançado corretamente')),
                ('is_horas_lancadas', models.BooleanField(default=False, help_text='Horas foram lançadas corretamente')),
                ('is_has_met_first_response_target', models.BooleanField(default=False, help_text='Meta do primeiro atendimento foi atingida')),
                ('is_resolution_target', models.BooleanField(default=False, help_text='Meta de resolução foi atingida')),
                ('is_atualizaca_logs_correto', models.BooleanField(default=False, help_text='Logs foram atualizados corretamente')),
                ('is_ticket_encerrado_corretamente', models.BooleanField(default=False, help_text='Ticket foi encerrado corretamente')),
                ('is_descricao_troubleshooting', models.BooleanField(default=False, help_text='Descrição do troubleshooting está adequada')),
                ('is_cliente_notificado', models.BooleanField(default=False, help_text='Cliente foi notificado adequadamente')),
                ('is_category_correto', models.BooleanField(default=False, help_text='Categorização está correta')),
                ('incident', models.ForeignKey(help_text='Incidente avaliado', on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='dw_analytics.incident')),
                ('user', models.ForeignKey(help_text='Usuário que realizou a avaliação', on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'f_avaliacao',
            },
        ),
    ]
