# Generated by Django 4.2.10 on 2025-01-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_filaatendimento_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='filaatendimento',
            name='codigo',
        ),
    ]
