// Medida para últimos 3 meses
Qtd Tickets últimos 3 meses = 
SWITCH (
    TRUE(),
    // Caso múltiplos anos selecionados
    ISFILTERED('d_Calendário'[Ano]) && NOT(HASONEVALUE('d_Calendário'[Ano])),
        CALCULATE(
            [qtd tickets],
            KEEPFILTERS('d_Calendário'[Ano] IN VALUES('d_Calendário'[Ano]))
        ),
    // Caso ano específico
    ISFILTERED('d_Calendário'[Ano]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Ano] = SELECTEDVALUE('d_Calendário'[Ano])
        ),
    // Caso mês específico
    ISFILTERED('d_Calendário'[Mês]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Mês] = SELECTEDVALUE('d_Calendário'[Mês])
        ),
    // Caso trimestre específico
    ISFILTERED('d_Calendário'[Trimestre]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Trimestre] = SELECTEDVALUE('d_Calendário'[Trimestre])
        ),
    // Caso semana específica
    ISFILTERED('d_Calendário'[Semana]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Semana] = SELECTEDVALUE('d_Calendário'[Semana])
        ),
    // Caso mês nome específico
    ISFILTERED('d_Calendário'[Mês nome]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Mês nome] = SELECTEDVALUE('d_Calendário'[Mês nome])
        ),
    // Caso mês nome e ano específicos
    ISFILTERED('d_Calendário'[Mês nome]) && ISFILTERED('d_Calendário'[Ano]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Mês nome] = SELECTEDVALUE('d_Calendário'[Mês nome]) 
            && 'd_Calendário'[Ano] = SELECTEDVALUE('d_Calendário'[Ano])
        ),
    // Caso padrão - últimos 3 meses
    CALCULATE(
        [qtd tickets],
        'd_Calendário'[Últimos 3 Meses] = TRUE()
    )
);

// Medida para últimos 6 meses
Qtd Tickets últimos 6 meses = 
SWITCH (
    TRUE(),
    // Caso múltiplos anos selecionados
    ISFILTERED('d_Calendário'[Ano]) && NOT(HASONEVALUE('d_Calendário'[Ano])),
        CALCULATE(
            [qtd tickets],
            KEEPFILTERS('d_Calendário'[Ano] IN VALUES('d_Calendário'[Ano]))
        ),
    // Caso ano específico
    ISFILTERED('d_Calendário'[Ano]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Ano] = SELECTEDVALUE('d_Calendário'[Ano])
        ),
    // Caso mês específico
    ISFILTERED('d_Calendário'[Mês]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Mês] = SELECTEDVALUE('d_Calendário'[Mês])
        ),
    // Caso trimestre específico
    ISFILTERED('d_Calendário'[Trimestre]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Trimestre] = SELECTEDVALUE('d_Calendário'[Trimestre])
        ),
    // Caso semana específica
    ISFILTERED('d_Calendário'[Semana]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Semana] = SELECTEDVALUE('d_Calendário'[Semana])
        ),
    // Caso mês nome específico
    ISFILTERED('d_Calendário'[Mês nome]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Mês nome] = SELECTEDVALUE('d_Calendário'[Mês nome])
        ),
    // Caso mês nome e ano específicos
    ISFILTERED('d_Calendário'[Mês nome]) && ISFILTERED('d_Calendário'[Ano]),
        CALCULATE(
            [qtd tickets],
            'd_Calendário'[Mês nome] = SELECTEDVALUE('d_Calendário'[Mês nome]) 
            && 'd_Calendário'[Ano] = SELECTEDVALUE('d_Calendário'[Ano])
        ),
    // Caso padrão - últimos 6 meses
    CALCULATE(
        [qtd tickets],
        'd_Calendário'[Últimos 6 Meses] = TRUE()
    )
)