// Medida original com problemas
/*
Qtd Tickets últimos 3 meses (Original) = 
// ... código original ...
*/

// Versão melhorada usando SWITCH e ISFILTERED
Qtd Tickets últimos 3 meses = 
VAR SelectedYear = SELECTEDVALUE('d_Calendário'[Ano], BLANK())
VAR SelectedMonth = SELECTEDVALUE('d_Calendário'[Mês], BLANK())
VAR SelectedQuarter = SELECTEDVALUE('d_Calendário'[Trimestre], BLANK())
VAR SelectedWeek = SELECTEDVALUE('d_Calendário'[Semana], BLANK())
VAR SelectedMonthName = SELECTEDVALUE('d_Calendário'[Mês nome], BLANK())

RETURN
SWITCH(
    TRUE(),
    // Caso 1: Mês e Ano selecionados
    AND(
        ISFILTERED('d_Calendário'[Ano]),
        ISFILTERED('d_Calendário'[Mês nome])
    ),
    CALCULATE(
        [qtd tickets],
        'd_Calendário'[Ano] = SelectedYear,
        'd_Calendário'[Mês nome] = SelectedMonthName
    ),
    
    // Caso 2: Apenas Ano selecionado
    ISFILTERED('d_Calendário'[Ano]),
    CALCULATE([qtd tickets], 'd_Calendário'[Ano] = SelectedYear),
    
    // Caso 3: Apenas Mês selecionado
    ISFILTERED('d_Calendário'[Mês]),
    CALCULATE([qtd tickets], 'd_Calendário'[Mês] = SelectedMonth),
    
    // Caso 4: Trimestre selecionado
    ISFILTERED('d_Calendário'[Trimestre]),
    CALCULATE([qtd tickets], 'd_Calendário'[Trimestre] = SelectedQuarter),
    
    // Caso 5: Semana selecionada
    ISFILTERED('d_Calendário'[Semana]),
    CALCULATE([qtd tickets], 'd_Calendário'[Semana] = SelectedWeek),
    
    // Caso 6: Apenas Mês nome selecionado
    ISFILTERED('d_Calendário'[Mês nome]),
    CALCULATE([qtd tickets], 'd_Calendário'[Mês nome] = SelectedMonthName),
    
    // Caso padrão: Últimos 3 meses quando nada está selecionado
    CALCULATE(
        [qtd tickets],
        'd_Calendário'[Últimos 3 Meses] = True()
    ),
    BLANK()
)

// Medida para últimos 6 meses
Qtd Tickets últimos 6 meses = 
VAR SelectedYear = SELECTEDVALUE('d_Calendário'[Ano], BLANK())
VAR SelectedMonth = SELECTEDVALUE('d_Calendário'[Mês], BLANK())
VAR SelectedQuarter = SELECTEDVALUE('d_Calendário'[Trimestre], BLANK())
VAR SelectedWeek = SELECTEDVALUE('d_Calendário'[Semana], BLANK())
VAR SelectedMonthName = SELECTEDVALUE('d_Calendário'[Mês nome], BLANK())

RETURN
SWITCH(
    TRUE(),
    // Caso 1: Mês e Ano selecionados
    AND(
        ISFILTERED('d_Calendário'[Ano]),
        ISFILTERED('d_Calendário'[Mês nome])
    ),
    CALCULATE(
        [qtd tickets],
        'd_Calendário'[Ano] = SelectedYear,
        'd_Calendário'[Mês nome] = SelectedMonthName
    ),
    
    // Caso 2: Apenas Ano selecionado
    ISFILTERED('d_Calendário'[Ano]),
    CALCULATE([qtd tickets], 'd_Calendário'[Ano] = SelectedYear),
    
    // Caso 3: Apenas Mês selecionado
    ISFILTERED('d_Calendário'[Mês]),
    CALCULATE([qtd tickets], 'd_Calendário'[Mês] = SelectedMonth),
    
    // Caso 4: Trimestre selecionado
    ISFILTERED('d_Calendário'[Trimestre]),
    CALCULATE([qtd tickets], 'd_Calendário'[Trimestre] = SelectedQuarter),
    
    // Caso 5: Semana selecionada
    ISFILTERED('d_Calendário'[Semana]),
    CALCULATE([qtd tickets], 'd_Calendário'[Semana] = SelectedWeek),
    
    // Caso 6: Apenas Mês nome selecionado
    ISFILTERED('d_Calendário'[Mês nome]),
    CALCULATE([qtd tickets], 'd_Calendário'[Mês nome] = SelectedMonthName),
    
    // Caso padrão: Últimos 6 meses quando nada está selecionado
    CALCULATE(
        [qtd tickets],
        'd_Calendário'[Últimos 6 Meses] = True()
    ),
    BLANK()
)