# Generated by Django 4.2.10 on 2025-01-22 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Analista',
                'verbose_name_plural': 'Analistas',
                'db_table': 'd_analista',
            },
        ),
        migrations.CreateModel(
            name='DFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Filas',
                'db_table': 'd_fila',
            },
        ),
        migrations.CreateModel(
            name='FTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(help_text='Número/identificador do ticket', max_length=50, unique=True)),
                ('data_abertura', models.DateTimeField()),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('horas_lancadas', models.DecimalField(decimal_places=2, help_text='Total de horas trabalhadas no ticket', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('contrato', models.CharField(help_text='Nome do contrato', max_length=50)),
                ('sla', models.DurationField(help_text='Tempo até o primeiro atendimento')),
                ('has_branched', models.DurationField(help_text='Tempo até a resolução')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.danalista')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'f_tickets',
            },
        ),
        migrations.CreateModel(
            name='DSortedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorted_tickets', to='tickets.fticket')),
            ],
            options={
                'verbose_name': 'Ticket Classificado',
                'verbose_name_plural': 'Tickets Classificados',
                'db_table': 'd_sorted_tickets',
            },
        ),
        migrations.AddField(
            model_name='danalista',
            name='fila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.dfila'),
        ),
    ]
