# Generated by Django 4.2.10 on 2025-01-22 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsortedticket',
            options={'verbose_name': 'Ticket Sorteado', 'verbose_name_plural': 'Tickets Sorteados'},
        ),
        migrations.RemoveField(
            model_name='dsortedticket',
            name='sort_date',
        ),
        migrations.RemoveField(
            model_name='dsortedticket',
            name='status',
        ),
        migrations.AddField(
            model_name='dsortedticket',
            name='analista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sorted_tickets', to='tickets.danalista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsortedticket',
            name='mes_ano',
            field=models.CharField(default='2025-01', help_text='Formato: YYYY-MM', max_length=7, validators=[django.core.validators.RegexValidator(message='O formato deve ser YYYY-MM', regex='^\\d{4}-(?:0[1-9]|1[0-2])$')]),
            preserve_default=False,
        ),
    ]
