# Generated by Django 4.2.10 on 2025-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_dsortedticket_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danalista',
            name='fila',
        ),
        migrations.AddField(
            model_name='danalista',
            name='filas',
            field=models.ManyToManyField(related_name='analistas', to='tickets.dfila', verbose_name='Filas'),
        ),
    ]
