# Generated by Django 4.2.10 on 2025-01-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('sys_id', models.CharField(help_text='ID único do incidente no ServiceNow', max_length=255, primary_key=True, serialize=False)),
                ('number', models.CharField(help_text='Número do incidente', max_length=255, null=True)),
                ('sys_created_on', models.DateTimeField(help_text='Data e hora de criação do registro', null=True)),
                ('sys_updated_on', models.DateTimeField(help_text='Data e hora da última atualização', null=True)),
                ('opened_at', models.DateTimeField(help_text='Data e hora de abertura do incidente', null=True)),
                ('closed_at', models.DateTimeField(help_text='Data e hora de fechamento do incidente', null=True)),
                ('resolved_at', models.DateTimeField(help_text='Data e hora de resolução do incidente', null=True)),
                ('state', models.IntegerField(help_text='Status numérico do incidente', null=True)),
                ('dv_state', models.CharField(help_text='Descrição do status do incidente', max_length=255, null=True)),
                ('priority', models.IntegerField(help_text='Nível de prioridade numérico', null=True)),
                ('dv_priority', models.CharField(help_text='Descrição do nível de prioridade', max_length=255, null=True)),
                ('impact', models.IntegerField(help_text='Nível de impacto numérico', null=True)),
                ('dv_impact', models.CharField(help_text='Descrição do nível de impacto', max_length=255, null=True)),
                ('urgency', models.IntegerField(help_text='Nível de urgência numérico', null=True)),
                ('dv_urgency', models.CharField(help_text='Descrição do nível de urgência', max_length=255, null=True)),
                ('incident_state', models.IntegerField(help_text='Estado do incidente numérico', null=True)),
                ('dv_incident_state', models.CharField(help_text='Descrição do estado do incidente', max_length=255, null=True)),
                ('short_description', models.TextField(help_text='Descrição curta do incidente', null=True)),
                ('description', models.TextField(help_text='Descrição completa do incidente', null=True)),
                ('close_notes', models.TextField(help_text='Notas de fechamento do incidente', null=True)),
                ('assigned_to', models.CharField(help_text='ID do usuário designado', max_length=255, null=True)),
                ('dv_assigned_to', models.CharField(help_text='Nome do usuário designado', max_length=255, null=True)),
                ('assignment_group', models.CharField(help_text='ID do grupo designado', max_length=255, null=True)),
                ('dv_assignment_group', models.CharField(help_text='Nome do grupo designado', max_length=255, null=True)),
                ('u_tipo_incidente', models.CharField(help_text='Tipo de incidente', max_length=255, null=True)),
                ('u_tempo_indisponivel', models.DateTimeField(help_text='Tempo total de indisponibilidade', null=True)),
                ('u_tempo_expurgo', models.DateTimeField(help_text='Tempo de expurgo do incidente', null=True)),
                ('u_fim_indisponibilidade', models.DateTimeField(help_text='Data e hora do fim da indisponibilidade', null=True)),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentSLA',
            fields=[
                ('sys_id', models.CharField(help_text='ID único do registro SLA no ServiceNow', max_length=255, primary_key=True, serialize=False)),
                ('task', models.CharField(help_text='ID da tarefa relacionada', max_length=255, null=True)),
                ('dv_task', models.CharField(help_text='Descrição da tarefa relacionada', max_length=255, null=True)),
                ('sla', models.CharField(help_text='ID do acordo SLA', max_length=255, null=True)),
                ('dv_sla', models.CharField(help_text='Descrição do acordo SLA', max_length=255, null=True)),
                ('stage', models.CharField(help_text='Estágio atual do SLA', max_length=255, null=True)),
                ('dv_stage', models.CharField(help_text='Descrição do estágio do SLA', max_length=255, null=True)),
                ('business_duration', models.DateTimeField(help_text='Duração em horário comercial', null=True)),
                ('dv_business_duration', models.CharField(help_text='Descrição da duração em horário comercial', max_length=255, null=True)),
                ('start_time', models.DateTimeField(help_text='Data e hora de início', null=True)),
                ('end_time', models.DateTimeField(help_text='Data e hora de término', null=True)),
                ('business_percentage', models.DecimalField(decimal_places=0, help_text='Percentual de conclusão em horário comercial', max_digits=18, null=True)),
                ('has_breached', models.BooleanField(help_text='Indica se o SLA foi violado', null=True)),
                ('active', models.BooleanField(help_text='Indica se o SLA está ativo', null=True)),
                ('sys_created_on', models.DateTimeField(help_text='Data e hora de criação do registro', null=True)),
                ('sys_updated_on', models.DateTimeField(help_text='Data e hora da última atualização', null=True)),
            ],
            options={
                'db_table': 'incident_sla',
            },
        ),
    ]
