# Generated by Django 4.2.10 on 2025-01-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_now', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='action_status',
            field=models.IntegerField(help_text='Status da ação', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='actions_taken',
            field=models.CharField(help_text='Ações tomadas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='active',
            field=models.BooleanField(help_text='Se o registro está ativo', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='activity_due',
            field=models.DateTimeField(help_text='Data prevista para atividade', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='additional_assignee_list',
            field=models.CharField(help_text='Lista de designados adicionais', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='agile_story',
            field=models.CharField(help_text='História ágil relacionada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='approval',
            field=models.CharField(help_text='Status de aprovação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='approval_history',
            field=models.CharField(help_text='Histórico de aprovações', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='approval_set',
            field=models.DateTimeField(help_text='Data de definição da aprovação', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='company',
            field=models.CharField(help_text='ID da empresa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='contract',
            field=models.CharField(help_text='ID do contrato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_action_status',
            field=models.CharField(help_text='Descrição do status da ação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_agile_story',
            field=models.CharField(help_text='Descrição da história ágil', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_approval',
            field=models.CharField(help_text='Descrição do status de aprovação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_company',
            field=models.CharField(help_text='Nome da empresa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_contract',
            field=models.CharField(help_text='Nome do contrato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_categoria_falha',
            field=models.CharField(help_text='Descrição da categoria de falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_detalhe_sub_categoria_da_falha',
            field=models.CharField(help_text='Detalhe da subcategoria de falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_origem',
            field=models.CharField(help_text='Descrição da origem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_sub_categoria_da_falha',
            field=models.CharField(help_text='Descrição da subcategoria de falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_justificativa_isolamento',
            field=models.CharField(help_text='Justificativa de isolamento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_origem',
            field=models.CharField(help_text='Origem do incidente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_tipo_indisponibilidade',
            field=models.CharField(help_text='Tipo de indisponibilidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='business_pause_duration',
            field=models.DateTimeField(help_text='Duração da pausa em horário comercial', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='business_time_left',
            field=models.DateTimeField(help_text='Tempo restante em horário comercial', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='duration',
            field=models.DateTimeField(help_text='Duração total', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='dv_business_pause_duration',
            field=models.CharField(help_text='Descrição da duração da pausa comercial', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='dv_business_time_left',
            field=models.CharField(help_text='Descrição do tempo restante comercial', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='dv_duration',
            field=models.CharField(help_text='Descrição da duração total', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='dv_pause_duration',
            field=models.CharField(help_text='Descrição da duração da pausa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='dv_schedule',
            field=models.CharField(help_text='Descrição do horário agendado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='dv_time_left',
            field=models.CharField(help_text='Descrição do tempo restante', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='dv_timezone',
            field=models.CharField(help_text='Descrição do fuso horário', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='original_breach_time',
            field=models.DateTimeField(help_text='Tempo original de violação', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='pause_duration',
            field=models.DateTimeField(help_text='Duração da pausa', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='pause_time',
            field=models.DateTimeField(help_text='Momento da pausa', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='percentage',
            field=models.DecimalField(decimal_places=0, help_text='Percentual de conclusão', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='planned_end_time',
            field=models.DateTimeField(help_text='Tempo planejado para término', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='schedule',
            field=models.CharField(help_text='Horário agendado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='sys_created_by',
            field=models.CharField(help_text='Criado por', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='sys_mod_count',
            field=models.IntegerField(help_text='Contagem de modificações', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='sys_tags',
            field=models.CharField(help_text='Tags do sistema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='sys_updated_by',
            field=models.CharField(help_text='Atualizado por', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='time_left',
            field=models.DateTimeField(help_text='Tempo restante', null=True),
        ),
        migrations.AddField(
            model_name='incidentsla',
            name='timezone',
            field=models.CharField(help_text='Fuso horário', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentsla',
            name='active',
            field=models.BooleanField(help_text='Se o SLA está ativo', null=True),
        ),
        migrations.AlterField(
            model_name='incidentsla',
            name='end_time',
            field=models.DateTimeField(help_text='Hora de término', null=True),
        ),
        migrations.AlterField(
            model_name='incidentsla',
            name='has_breached',
            field=models.BooleanField(help_text='Se o SLA foi violado', null=True),
        ),
    ]
