# Generated by Django 4.2.10 on 2025-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_now', '0002_incident_action_status_incident_actions_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='business_duration',
            field=models.DateTimeField(help_text='Duração em horário comercial', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='business_impact',
            field=models.CharField(help_text='Impacto comercial', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='business_service',
            field=models.CharField(help_text='Serviço comercial', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='business_stc',
            field=models.IntegerField(help_text='STC comercial', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='calendar_duration',
            field=models.DateTimeField(help_text='Duração do calendário', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='calendar_stc',
            field=models.IntegerField(help_text='STC do calendário', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='caller_id',
            field=models.CharField(help_text='ID do chamador', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(help_text='Categoria', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='cause',
            field=models.CharField(help_text='Causa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='caused_by',
            field=models.CharField(help_text='Causado por', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='child_incidents',
            field=models.IntegerField(help_text='Incidentes filhos', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='close_code',
            field=models.CharField(help_text='Código de fechamento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_by',
            field=models.CharField(help_text='Fechado por', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='cmdb_ci',
            field=models.CharField(help_text='CI do CMDB', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='comments',
            field=models.CharField(help_text='Comentários', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='comments_and_work_notes',
            field=models.CharField(help_text='Comentários e notas de trabalho', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='contact_type',
            field=models.CharField(help_text='Tipo de contato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='correlation_display',
            field=models.CharField(help_text='Exibição de correlação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='correlation_id',
            field=models.CharField(help_text='ID de correlação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='delivery_plan',
            field=models.CharField(help_text='Plano de entrega', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='delivery_task',
            field=models.CharField(help_text='Tarefa de entrega', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='due_date',
            field=models.DateTimeField(help_text='Data de vencimento', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_business_duration',
            field=models.CharField(help_text='Descrição da duração em horário comercial', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_business_service',
            field=models.CharField(help_text='Descrição do serviço comercial', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_calendar_duration',
            field=models.CharField(help_text='Descrição da duração do calendário', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_caller_id',
            field=models.CharField(help_text='Descrição do chamador', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_category',
            field=models.CharField(help_text='Descrição da categoria', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_caused_by',
            field=models.CharField(help_text='Descrição do causador', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_close_code',
            field=models.CharField(help_text='Descrição do código de fechamento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_closed_by',
            field=models.CharField(help_text='Descrição de quem fechou', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_cmdb_ci',
            field=models.CharField(help_text='Descrição do CI do CMDB', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_contact_type',
            field=models.CharField(help_text='Descrição do tipo de contato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_delivery_plan',
            field=models.CharField(help_text='Descrição do plano de entrega', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_delivery_task',
            field=models.CharField(help_text='Descrição da tarefa de entrega', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_escalation',
            field=models.CharField(help_text='Descrição da escalação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_hold_reason',
            field=models.CharField(help_text='Descrição do motivo de espera', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_location',
            field=models.CharField(help_text='Descrição da localização', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_major_incident_state',
            field=models.CharField(help_text='Descrição do estado de incidente maior', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_notify',
            field=models.CharField(help_text='Descrição da notificação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_parent',
            field=models.CharField(help_text='Descrição do pai', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_parent_incident',
            field=models.CharField(help_text='Descrição do incidente pai', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_problem_id',
            field=models.CharField(help_text='Descrição do ID do problema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_promoted_by',
            field=models.CharField(help_text='Descrição de quem promoveu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_proposed_by',
            field=models.CharField(help_text='Descrição de quem propôs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_reopened_by',
            field=models.CharField(help_text='Descrição de quem reabriu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_resolved_by',
            field=models.CharField(help_text='Nome do usuário que resolveu o incidente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_rfc',
            field=models.CharField(help_text='Descrição do RFC', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_route_reason',
            field=models.CharField(help_text='Descrição do motivo da rota', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_scr_vendor',
            field=models.CharField(help_text='Descrição do fornecedor SCR', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_service_offering',
            field=models.CharField(help_text='Descrição da oferta de serviço', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_severity',
            field=models.CharField(help_text='Descrição da severidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_sn_ind_tsm_core_stage',
            field=models.CharField(help_text='Descrição do estágio principal TSM', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_subcategory',
            field=models.CharField(help_text='Descrição da subcategoria', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_sys_class_name',
            field=models.CharField(help_text='Descrição do nome da classe do sistema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_time_worked',
            field=models.CharField(help_text='Descrição do tempo trabalhado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_trigger_rule',
            field=models.CharField(help_text='Descrição da regra de gatilho', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_b2b_downtime',
            field=models.CharField(help_text='Descrição do tempo de inatividade B2B', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_bloquear_ticket',
            field=models.CharField(help_text='Descrição do bloqueio de ticket', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_case_ticket_vivo',
            field=models.CharField(help_text='Descrição do ticket Vivo do caso', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_categoria_da_falha',
            field=models.CharField(help_text='Descrição da categoria da falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_chamado_tratado_por_analista',
            field=models.CharField(help_text='Descrição do chamado tratado por analista', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_cmdb_ci',
            field=models.CharField(help_text='Descrição do CI do CMDB', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_contato_autorizado_lca',
            field=models.CharField(help_text='Descrição do contato autorizado LCA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_customer_pending_time',
            field=models.CharField(help_text='Descrição do tempo pendente do cliente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_detail_subcategory',
            field=models.CharField(help_text='Descrição da subcategoria de detalhes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_duration',
            field=models.CharField(help_text='Descrição da duração', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_expected_resolution_time',
            field=models.CharField(help_text='Descrição do tempo esperado de resolução', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_expected_response_time',
            field=models.CharField(help_text='Descrição do tempo esperado de resposta', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_expected_service_time',
            field=models.CharField(help_text='Descrição do tempo esperado de serviço', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_grupo',
            field=models.CharField(help_text='Descrição do grupo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_procedencia',
            field=models.CharField(help_text='Descrição da procedência', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_product_category',
            field=models.CharField(help_text='Descrição da categoria do produto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_product_subcategory',
            field=models.CharField(help_text='Descrição da subcategoria do produto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_product_subcategory_detail',
            field=models.CharField(help_text='Descrição do detalhe da subcategoria do produto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_product_vivo',
            field=models.CharField(help_text='Descrição do produto Vivo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_rede',
            field=models.CharField(help_text='Descrição da rede', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_reincidencia',
            field=models.CharField(help_text='Descrição da reincidência', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_resolution_time',
            field=models.CharField(help_text='Descrição do tempo de resolução', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_response_time',
            field=models.CharField(help_text='Descrição do tempo de resposta', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_rpt_deteccao_inc_ate_ticket',
            field=models.CharField(help_text='Descrição da detecção do incidente até o ticket', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_rpt_tempo_de_abertura_encerramento',
            field=models.CharField(help_text='Descrição do tempo de abertura até encerramento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_rpt_tempo_de_deteccao_do_inc_ate_a_abertura_do_ticket',
            field=models.CharField(help_text='Descrição do tempo de detecção do incidente até a abertura do ticket', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_rpt_tempo_de_processamento_da_automacao',
            field=models.CharField(help_text='Descrição do tempo de processamento da automação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_rpt_tempo_de_processamento_da_automacao_ate_abertura_do_ticket',
            field=models.CharField(help_text='Descrição do tempo de processamento da automação até a abertura do ticket', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_rpt_tempo_detecao_hora',
            field=models.CharField(help_text='Descrição do tempo de detecção em horas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_service_time',
            field=models.CharField(help_text='Descrição do tempo de serviço', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_sla_tratativa',
            field=models.CharField(help_text='Descrição do SLA de tratativa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_suport_group_name',
            field=models.CharField(help_text='Descrição do nome do grupo de suporte', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_tipo_de_procedencia',
            field=models.CharField(help_text='Descrição do tipo de procedência', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_u_unidade_caixa',
            field=models.CharField(help_text='Descrição da Unidade Caixa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_universal_request',
            field=models.CharField(help_text='Descrição da solicitação universal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_upon_approval',
            field=models.CharField(help_text='Descrição após aprovação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='dv_upon_reject',
            field=models.CharField(help_text='Descrição após rejeição', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation',
            field=models.IntegerField(help_text='Escalação', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='expected_start',
            field=models.DateTimeField(help_text='Início esperado', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='follow_up',
            field=models.DateTimeField(help_text='Acompanhamento', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='group_list',
            field=models.CharField(help_text='Lista de grupos', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='hold_reason',
            field=models.IntegerField(help_text='Motivo de espera', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='knowledge',
            field=models.BooleanField(help_text='Conhecimento', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='lessons_learned',
            field=models.TextField(help_text='Lições aprendidas', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(help_text='Localização', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='made_sla',
            field=models.BooleanField(help_text='SLA cumprido', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='major_incident_state',
            field=models.CharField(help_text='Estado de incidente maior', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='needs_attention',
            field=models.BooleanField(help_text='Precisa de atenção', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='notify',
            field=models.IntegerField(help_text='Notificar', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='origin_id',
            field=models.CharField(help_text='ID de origem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='origin_table',
            field=models.CharField(help_text='Tabela de origem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='overview',
            field=models.TextField(help_text='Visão geral', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='parent',
            field=models.CharField(help_text='Pai', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='parent_incident',
            field=models.CharField(help_text='Incidente pai', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='problem_id',
            field=models.CharField(help_text='ID do problema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='promoted_by',
            field=models.CharField(help_text='Promovido por', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='promoted_on',
            field=models.DateTimeField(help_text='Promovido em', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='proposed_by',
            field=models.CharField(help_text='Proposto por', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='proposed_on',
            field=models.DateTimeField(help_text='Proposto em', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reassignment_count',
            field=models.IntegerField(help_text='Contagem de reatribuições', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reopen_count',
            field=models.IntegerField(help_text='Contagem de reaberturas', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reopened_by',
            field=models.CharField(help_text='Reaberto por', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reopened_time',
            field=models.DateTimeField(help_text='Hora de reabertura', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.CharField(help_text='ID do usuário que resolveu o incidente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='rfc',
            field=models.CharField(help_text='RFC', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='route_reason',
            field=models.IntegerField(help_text='Motivo da rota', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scr_vendor',
            field=models.CharField(help_text='Fornecedor SCR', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scr_vendor_closed_at',
            field=models.DateTimeField(help_text='Fechado pelo fornecedor SCR em', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scr_vendor_opened_at',
            field=models.DateTimeField(help_text='Aberto pelo fornecedor SCR em', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scr_vendor_point_of_contact',
            field=models.CharField(help_text='Ponto de contato do fornecedor SCR', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scr_vendor_resolved_at',
            field=models.DateTimeField(help_text='Resolvido pelo fornecedor SCR em', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scr_vendor_ticket',
            field=models.CharField(help_text='Ticket do fornecedor SCR', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='service_offering',
            field=models.CharField(help_text='Oferta de serviço', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.IntegerField(help_text='Severidade', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='skills',
            field=models.CharField(help_text='Habilidades', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_due',
            field=models.DateTimeField(help_text='Vencimento do SLA', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sn_ind_tsm_core_incident',
            field=models.BooleanField(help_text='Incidente principal TSM', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sn_ind_tsm_core_stage',
            field=models.CharField(help_text='Estágio principal TSM', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='subcategory',
            field=models.CharField(help_text='Subcategoria', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sys_class_name',
            field=models.CharField(help_text='Nome da classe do sistema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sys_domain',
            field=models.CharField(help_text='Domínio do sistema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='sys_domain_path',
            field=models.CharField(help_text='Caminho do domínio do sistema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='task_effective_number',
            field=models.CharField(help_text='Número efetivo da tarefa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='time_worked',
            field=models.DateTimeField(help_text='Tempo trabalhado', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='timeline',
            field=models.TextField(help_text='Linha do tempo', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='trigger_rule',
            field=models.CharField(help_text='Regra de gatilho', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_alert_ingest',
            field=models.DateTimeField(help_text='Ingestão de alerta', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_alert_name',
            field=models.TextField(help_text='Nome do alerta', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_anexo',
            field=models.CharField(help_text='Anexo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_b2b_downtime',
            field=models.DateTimeField(help_text='Tempo de inatividade B2B', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_b2b_purge_report',
            field=models.BooleanField(help_text='Relatório de purga B2B', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_bloquear_ticket',
            field=models.CharField(help_text='Bloquear ticket', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_c_digo_da_falha',
            field=models.CharField(help_text='Código da falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_case_ticket_vivo',
            field=models.CharField(help_text='Ticket Vivo do caso', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_case_vivo_ticket_number',
            field=models.CharField(help_text='Número do ticket Vivo do caso', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_categoria_da_falha',
            field=models.CharField(help_text='Categoria da falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_categorizacao_n1',
            field=models.CharField(help_text='Categorização N1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_categorizacao_n2',
            field=models.CharField(help_text='Categorização N2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_categorizacao_n3',
            field=models.CharField(help_text='Categorização N3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_cep',
            field=models.CharField(help_text='CEP', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_chamado_tratado_por_analista',
            field=models.CharField(help_text='Chamado tratado por analista', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_cidade',
            field=models.CharField(help_text='Cidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_classificacao_da_unidade',
            field=models.CharField(help_text='Classificação da unidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_cloud_provider',
            field=models.CharField(help_text='Provedor de nuvem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_cmdb_ci',
            field=models.CharField(help_text='CI do CMDB', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_cnpj',
            field=models.CharField(help_text='CNPJ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_comentarios_adicionais',
            field=models.CharField(help_text='Comentários adicionais', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_comment_inserted',
            field=models.BooleanField(help_text='Comentário inserido', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_company_name',
            field=models.CharField(help_text='Nome da empresa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_complaint',
            field=models.CharField(help_text='Reclamação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_complaint_sub',
            field=models.CharField(help_text='Sub-reclamação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_contato_autorizado_lca',
            field=models.CharField(help_text='Contato autorizado LCA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_contato_email',
            field=models.CharField(help_text='Email do contato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_contato_nome',
            field=models.CharField(help_text='Nome do contato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_contato_telefone',
            field=models.CharField(help_text='Telefone do contato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_contatos_adicionais',
            field=models.CharField(help_text='Contatos adicionais', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_customer_pending_time',
            field=models.DateTimeField(help_text='Tempo pendente do cliente', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_data_demisto',
            field=models.DateTimeField(help_text='Data Demisto', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_data_normalizacao_servico',
            field=models.DateTimeField(help_text='Data de normalização do serviço', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_data_prevista_para_atendimento',
            field=models.CharField(help_text='Data prevista para atendimento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_descri_o_do_problema',
            field=models.CharField(help_text='Descrição do problema', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_designador',
            field=models.CharField(help_text='Designador', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_designador_do_circuito',
            field=models.CharField(help_text='Designador do circuito', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_detail_subcategory',
            field=models.CharField(help_text='Subcategoria de detalhes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_detalhe_23',
            field=models.CharField(help_text='Detalhe 23', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_detalhe_solucoes',
            field=models.CharField(help_text='Detalhe das soluções', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_detalhe_sub_categoria_da_falha',
            field=models.CharField(help_text='Detalhe da subcategoria da falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_detalhes_adicionais',
            field=models.CharField(help_text='Detalhes adicionais', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_duration',
            field=models.DateTimeField(help_text='Duração', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_endereco_da_localidade',
            field=models.CharField(help_text='Endereço da localidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_endereco_da_unidade',
            field=models.CharField(help_text='Endereço da unidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_endereco_do_ponto',
            field=models.CharField(help_text='Endereço do ponto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_event_action',
            field=models.CharField(help_text='Ação do evento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_event_ingest',
            field=models.DateTimeField(help_text='Ingestão do evento', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_expected_resolution_time',
            field=models.DateTimeField(help_text='Tempo esperado de resolução', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_expected_response_time',
            field=models.DateTimeField(help_text='Tempo esperado de resposta', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_expected_service_time',
            field=models.DateTimeField(help_text='Tempo esperado de serviço', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_grupo',
            field=models.CharField(help_text='Grupo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_hostname',
            field=models.CharField(help_text='Nome do host', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_da_unidade',
            field=models.CharField(help_text='ID da unidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_demisto',
            field=models.CharField(help_text='ID Demisto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_do_ponto',
            field=models.CharField(help_text='ID do ponto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_do_ponto_ii',
            field=models.CharField(help_text='ID do ponto II', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_do_solicitante',
            field=models.CharField(help_text='ID do solicitante', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_sigla_da_unidade',
            field=models.CharField(help_text='Sigla da unidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_vantive',
            field=models.CharField(help_text='ID Vantive', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_id_vgr',
            field=models.CharField(help_text='ID VGR', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_identificacao_do_hardware',
            field=models.CharField(help_text='Identificação do hardware', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_identificacao_do_ponto',
            field=models.CharField(help_text='Identificação do ponto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_impact_do_ticket',
            field=models.CharField(help_text='Impacto do ticket', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_inicio_sprint',
            field=models.DateField(help_text='Início do sprint', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_integration',
            field=models.BooleanField(help_text='Integração', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_ip_destination',
            field=models.CharField(help_text='IP de destino', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_ip_origin',
            field=models.CharField(help_text='IP de origem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_line',
            field=models.CharField(help_text='Linha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_link_type',
            field=models.CharField(help_text='Tipo de link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_lp',
            field=models.CharField(help_text='LP', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_nome_da_unidade',
            field=models.CharField(help_text='Nome da unidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_nome_do_ponto',
            field=models.CharField(help_text='Nome do ponto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_nome_do_respons_vel_pela_abertura_do_chamado',
            field=models.CharField(help_text='Nome do responsável pela abertura do chamado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_number_mass',
            field=models.CharField(help_text='Número MASS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_number_sigitm',
            field=models.CharField(help_text='Número SIGITM', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_numero_do_contrato_dados',
            field=models.CharField(help_text='Número do contrato de dados', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_numero_do_contrato_voz',
            field=models.CharField(help_text='Número do contrato de voz', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_observacao_da_perda_do_sla',
            field=models.CharField(help_text='Observação da perda do SLA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_opened_month',
            field=models.CharField(help_text='Mês de abertura', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_opening_reason',
            field=models.CharField(help_text='Motivo de abertura', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_operational_system',
            field=models.CharField(help_text='Sistema operacional', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_port_destination',
            field=models.CharField(help_text='Porta de destino', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_port_origin',
            field=models.CharField(help_text='Porta de origem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_portal_solicitacoes',
            field=models.BooleanField(help_text='Portal de solicitações', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_procedencia',
            field=models.CharField(help_text='Procedência', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_product_category',
            field=models.CharField(help_text='Categoria do produto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_product_subcategory',
            field=models.CharField(help_text='Subcategoria do produto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_product_subcategory_detail',
            field=models.CharField(help_text='Detalhe da subcategoria do produto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_product_vivo',
            field=models.CharField(help_text='Produto Vivo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_produto_n1',
            field=models.CharField(help_text='Produto N1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_produto_n2',
            field=models.CharField(help_text='Produto N2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_produto_n3',
            field=models.CharField(help_text='Produto N3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_rede',
            field=models.CharField(help_text='Rede', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_reincidencia',
            field=models.CharField(help_text='Reincidência', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_resent_remedy',
            field=models.IntegerField(help_text='Remédio reenviado', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_resolution_time',
            field=models.DateTimeField(help_text='Tempo de resolução', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_response_time',
            field=models.DateTimeField(help_text='Tempo de resposta', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_rpt_deteccao_inc_ate_ticket',
            field=models.DateTimeField(help_text='Detecção do incidente até o ticket', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_rpt_tempo_de_abertura_encerramento',
            field=models.DateTimeField(help_text='Tempo de abertura até encerramento', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_rpt_tempo_de_deteccao_do_inc_ate_a_abertura_do_ticket',
            field=models.DateTimeField(help_text='Tempo de detecção do incidente até a abertura do ticket', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_rpt_tempo_de_processamento_da_automacao',
            field=models.DateTimeField(help_text='Tempo de processamento da automação', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_rpt_tempo_de_processamento_da_automacao_ate_abertura_do_ticket',
            field=models.DateTimeField(help_text='Tempo de processamento da automação até a abertura do ticket', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_rpt_tempo_detecao_hora',
            field=models.DateTimeField(help_text='Tempo de detecção em horas', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_serial_do_equipamento',
            field=models.CharField(help_text='Serial do equipamento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_serial_number',
            field=models.CharField(help_text='Número de série', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_service_time',
            field=models.DateTimeField(help_text='Tempo de serviço', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_service_type',
            field=models.CharField(help_text='Tipo de serviço', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_severidade_do_chamado',
            field=models.CharField(help_text='Severidade do chamado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_sigla_da_unidade',
            field=models.CharField(help_text='Sigla da unidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_signal_rule_description',
            field=models.TextField(help_text='Descrição da regra de sinal', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_sla_tratativa',
            field=models.CharField(help_text='SLA de tratativa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_source_instance',
            field=models.CharField(help_text='Instância de origem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_sub_categoria_da_falha',
            field=models.CharField(help_text='Subcategoria da falha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_suport_group_name',
            field=models.CharField(help_text='Nome do grupo de suporte', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_telefone_do_responsavel',
            field=models.CharField(help_text='Telefone do responsável', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_tempo_total_da_tratativa',
            field=models.CharField(help_text='Tempo total da tratativa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_ticket_infinity',
            field=models.CharField(help_text='Ticket Infinity', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_ticket_infinity_number',
            field=models.CharField(help_text='Número do Ticket Infinity', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_ticket_remedy_number',
            field=models.CharField(help_text='Número do Ticket Remedy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_ticket_sigtm_number',
            field=models.CharField(help_text='Número do Ticket SIGTM', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_tipo_de_procedencia',
            field=models.CharField(help_text='Tipo de procedência', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_tipo_de_servico',
            field=models.CharField(help_text='Tipo de serviço', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_torre_de_atendimento',
            field=models.CharField(help_text='Torre de atendimento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_type_ritm_or_incident',
            field=models.CharField(help_text='Tipo de RITM ou incidente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_uf',
            field=models.CharField(help_text='UF', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_unidade_caixa',
            field=models.CharField(help_text='Unidade Caixa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_user_agent',
            field=models.CharField(help_text='Agente do usuário', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_vendor_ticket',
            field=models.CharField(help_text='Ticket do fornecedor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='u_vita_it',
            field=models.BooleanField(help_text='VITA IT', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='universal_request',
            field=models.CharField(help_text='Solicitação universal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='upon_approval',
            field=models.CharField(help_text='Após aprovação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='upon_reject',
            field=models.CharField(help_text='Após rejeição', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='user_input',
            field=models.CharField(help_text='Entrada do usuário', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='watch_list',
            field=models.CharField(help_text='Lista de observação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='work_end',
            field=models.DateTimeField(help_text='Fim do trabalho', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='work_notes',
            field=models.CharField(help_text='Notas de trabalho', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='work_notes_list',
            field=models.CharField(help_text='Lista de notas de trabalho', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='work_start',
            field=models.DateTimeField(help_text='Início do trabalho', null=True),
        ),
    ]
