# Generated by Django 4.2.10 on 2025-01-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('access', '0007_user_fila_atendimento_user_is_gestor_user_is_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fila_atendimento',
        ),
        migrations.AddField(
            model_name='user',
            name='fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cadastro.filaatendimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cadastro.empresa'),
        ),
    ]
