# Generated by Django 4.2.10 on 2025-01-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_remove_user_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='empresa',
        ),
    ]
