# Generated by Django 4.2.10 on 2025-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_rename_user_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_access',
            field=models.BooleanField(default=True),
        ),
    ]
