# Generated by Django 4.2.10 on 2025-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_user_first_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
