# Generated by Django 4.2.10 on 2025-01-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_user_is_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='empresa',
        ),
    ]
