# Generated by Django 4.2.10 on 2025-01-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_empresa_codigo_remove_filaatendimento_codigo'),
        ('access', '0012_remove_user_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fila',
        ),
        migrations.AddField(
            model_name='user',
            name='filas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='cadastro.filaatendimento'),
        ),
    ]
