# Generated by Django 4.2.10 on 2025-01-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dw_analystics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premissas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_incidents', models.IntegerField(help_text='Quantidade de incidentes a serem sorteados')),
                ('assignment', models.ForeignKey(help_text='Assignment Group relacionado', on_delete=django.db.models.deletion.PROTECT, related_name='premissas', to='dw_analystics.assignmentgroup')),
            ],
            options={
                'verbose_name': 'Premissa',
                'verbose_name_plural': 'Premissas',
                'db_table': 'd_premissas',
            },
        ),
    ]
