# Generated by Django 4.2.10 on 2025-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0003_alter_premissas_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='premissas',
            name='is_atualizaca_logs_correto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_category_correto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_cliente_notificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_contrato_lancado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_descricao_troubleshooting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_has_met_first_response_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_horas_lancadas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_resolution_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premissas',
            name='is_ticket_encerrado_corretamente',
            field=models.BooleanField(default=True),
        ),
    ]
