# Generated by Django 4.2.10 on 2025-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0002_assignmentgroup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='sla_atendimento',
            field=models.BooleanField(blank=True, help_text='Identifica se o SLA de atendimento foi atendido.', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sla_resolucao',
            field=models.BooleanField(blank=True, help_text='Identifica se o SLA de resolução foi atendido.', null=True),
        ),
    ]
