# Generated by Django 4.2.10 on 2025-01-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0003_alter_incident_sla_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assignment_group',
            field=models.ForeignKey(default=1, help_text='Grupo de atendimento', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='dw_analytics.assignmentgroup'),
            preserve_default=False,
        ),
    ]
