# Generated by Django 4.2.10 on 2025-01-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0004_incident_assignment_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='dv_u_categoria_falha',
            new_name='dv_u_categoria_da_falha',
        ),
    ]
