# Generated by Django 4.2.10 on 2025-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0005_rename_dv_u_categoria_falha_incident_dv_u_categoria_da_falha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='company',
            field=models.CharField(help_text='ID Do Cliente', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='dv_u_categoria_da_falha',
            field=models.CharField(blank=True, help_text='Categoria da falha', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='dv_u_detalhe_sub_categoria_da_falha',
            field=models.CharField(help_text='Detalhe da SubCategoria da flaha.', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='dv_u_sub_categoria_da_falha',
            field=models.CharField(blank=True, help_text='Sub Categoria da falha', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.CharField(help_text='Número do chamado no ServiceNow', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='u_origem',
            field=models.CharField(help_text='Torre de atendimento', max_length=255),
        ),
    ]
