# Generated by Django 4.2.10 on 2025-01-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0006_alter_incident_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='assignment_group',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved_by',
        ),
        migrations.AddField(
            model_name='incident',
            name='assignment_group_id',
            field=models.CharField(blank=True, help_text='Grupo de atendimento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='contract_id',
            field=models.CharField(blank=True, help_text='ID Do Contrato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='number',
            field=models.CharField(default=1, help_text='Número do chamado no ServiceNow', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by_id',
            field=models.CharField(blank=True, help_text='ID Do analista', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='company',
            field=models.CharField(blank=True, help_text='ID Do Cliente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='dv_u_detalhe_sub_categoria_da_falha',
            field=models.CharField(blank=True, help_text='Detalhe da SubCategoria da falha', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='u_origem',
            field=models.CharField(blank=True, help_text='Torre de atendimento', max_length=255, null=True),
        ),
    ]
