# Generated by Django 4.2.10 on 2025-01-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0007_remove_incident_assignment_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='assignment_group_id',
            new_name='assignment_group',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='contract_id',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='resolved_by_id',
            new_name='resolved_by',
        ),
    ]
