# Generated by Django 4.2.10 on 2025-02-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_analytics', '0008_rename_assignment_group_id_incident_assignment_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(help_text='ID da Empresa', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(help_text='ID do Contrato', max_length=255, primary_key=True, serialize=False),
        ),
    ]
